### ISSUE TITLE
How do I specify an access modifier for a property setter

### ISSUE THREAD

**Issue by FingerCaster** [ful-stackz/SharpCode#16]

**Comment by FingerCaster** [comment]
Hello,@ful-stackz! Recently，I tried to change the access modifier of setter for Property but now I have encountered a problem, which told me that 'accessibility modifier of the accessor must be more restrictive than the property'.I don't know how to judge them in Rosyln so I wrote a function to do this by myself. 
And i have founded a bug，in the AccessModifier enumeration, 'PrivateInternal' should be 'PrivateProtected'. The access modifier PrivateInternal does not exist in CSharp. 
I will create a pull request for you. Please contact me if you have any suggestions.Thanks.

**Comment by ful-stackz** [comment]
Thank you so much for taking your time to discover, figure it out and make a contribution! PR #17 looks great and I've already merged it! Thanks again 🙏
